<?php
	$ci = &get_instance();
	$config = array(
		//'header_on' => FALSE,
		//'footer_on' => FALSE,
	);
	$ci->load->library('hits/pdf', $config);
	$ci->pdf->SetSubject('TCPDF Tutorial');
	$ci->pdf->SetKeywords('TCPDF, PDF, example, test, guide');
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->SetFont('helvetica', '', 9);
	$ci->pdf->AddPage();
	$ci->pdf->Multicell(190, 8, 'CONCURSO DE CARGOS DE LA DIRECCION GENERAL DE ESTADISTICAS-MINISTERIO DE ECONOMIA, INFRAESTRUCTURA Y SERVICIOS PUBLICOS CONSTANCIA DE INSCRIPCION', 1, 'L', false, 1, '', '', true, 0, true);
	$ci->pdf->Ln(3);
	$ci->pdf->SetFillColor(200, 200, 200);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->Cell(190, 6, 'DATOS DEL CARGO A CONCURSAR', 1, 1, 'C', TRUE);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->Cell(20, 6, 'Ministerio', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(170, 6, 'Ministerio de Economía, Infraestructura y Servicios Públicos', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Organismo', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(170, 6, 'Dirección General de Estadísticas', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Nivel', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(175, 6, 'Departamento Demográfico y Social', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Cargo', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(175, 6, 'Jefe de Departamento', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Orden', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(25, 6, '41', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Escalafón', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(25, 6, '02', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'Agrupamiento', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(25, 6, 'P', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(30, 6, 'Función Jerárquica', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(25, 6, 'I', 1, 1, 'L', FALSE);
	$ci->pdf->Ln(3);
	$ci->pdf->SetFillColor(200, 200, 200);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->Cell(190, 6, 'DATOS PERSONALES', 1, 1, 'C', TRUE);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->Cell(20, 6, 'Documento', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'CUIT', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'Fecha de Nac.', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(10, 6, 'Edad', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'Grupo Sanguineo', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(10, 6, 'Factor', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 1, 'L', FALSE);

	$ci->pdf->Cell(15, 6, 'Sexo', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'Extranjero', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(30, 6, 'Nacionalidad', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(40, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'Estado civil', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(35, 6, '', 1, 1, 'L', FALSE);

	$ci->pdf->Cell(25, 6, 'Localidad de Nac.', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(40, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'Provincia de Nac.', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(40, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'País de Nac.', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(35, 6, '', 1, 1, 'L', FALSE);

	$ci->pdf->Cell(30, 6, 'Apellido y Nombre', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(160, 6, '', 1, 1, 'L', FALSE);	
	$ci->pdf->Cell(30, 6, 'Domicilio', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(130, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(10, 6, 'C.P.', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(20, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(30, 6, 'Localidad', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(75, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(30, 6, 'Provincia', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(55, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Teléfono', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(25, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Celular', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(25, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Email', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(80, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Teléfono Lab.', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(25, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Centrex', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Interno', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Profesion', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(65, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(85, 6, 'Posee Antecedentes Penales', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(85, 6, 'Se Acogió al Retiro Voluntario', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(10, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->SetFillColor(200, 200, 200);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->Cell(190, 6, 'DATOS DEL CARGO', 1, 1, 'C', TRUE);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->Cell(20, 6, 'Ministerio', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(170, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Organismo', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(170, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Nivel', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(175, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Cargo', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(175, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Decreto', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(20, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(15, 6, 'Orden', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Escalafón', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(25, 6, 'Agrupamiento', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(30, 6, 'Función Jerárquica', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(20, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(40, 6, 'Equivalente Remunerativo', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(20, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(30, 6, 'Observaciones', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(100, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->SetFillColor(200, 200, 200);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->Cell(190, 6, 'ANTECEDENTES DE ESTUDIOS', 1, 1, 'C', TRUE);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->Cell(95, 6, 'Antecedente', 1, 0, 'C', TRUE);
	$ci->pdf->Cell(95, 6, 'Titulo', 1, 1, 'C', TRUE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 0, 'L', FALSE);
	$ci->pdf->Cell(95, 6, '', 1, 1, 'L', FALSE);
	$ci->pdf->AddPage();
	$ci->pdf->SetFillColor(200, 200, 200);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->Cell(190, 6, 'ANTECEDENTES DE ESTUDIOS', 1, 1, 'C', TRUE);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->Cell(175, 6, 'Acredita Antecedentes Docentes (Secundarios, Terciarios, Universitarios)', 1, 0, 'L', TRUE);
	$ci->pdf->Cell(15, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->SetFillColor(200, 200, 200);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->Cell(190, 6, 'ANTECEDENTES POR FORMACION LABORAL', 1, 1, 'C', TRUE);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->SetFillColor(200, 200, 200);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->Cell(190, 6, 'OBSERVACIONES', 1, 1, 'C', TRUE);
	$ci->pdf->SetFont('helvetica', 'B', 8);
	$ci->pdf->SetFillColor(230, 230, 230);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Cell(190, 6, '', 1, 1, 'C', FALSE);
	$ci->pdf->Ln(12);
	$ci->pdf->Cell(95, 6, 'Firma y Aclaración del Postulante', 1, 0, 'C', TRUE);
	$ci->pdf->Cell(95, 6, 'Firma y Aclaración de la Autoridad de Aplicación', 1, 1, 'C', TRUE);
	$ci->pdf->Multicell(95, 16, '', 1, 'L', false, 0, '', '', true, 0, true);
	$ci->pdf->Multicell(95, 16, '', 1, 'L', false, 0, '', '', true, 0, true);

	$ci->pdf->Ln(3);
	
	/*$ci->pdf->Line(10, 40, 200, 40);
	$ci->pdf->Ln(2);
	$ci->pdf->SetFont('helvetica', 'B', 10);
	$ci->pdf->Cell(190, 7, 'Detalle', 0, 1, 'L', TRUE);
	$ci->pdf->Ln(2);
	$ci->pdf->SetFont('helvetica', '', 9);
	$ci->pdf->Cell(30, 6, 'Tipo de Actuación : ', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(65, 6, $actuacion['nombreActuacionTipo'], 0, 0, 'L', FALSE);
	$ci->pdf->Cell(40, 6, 'Cantidad total de folios :', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(100, 6, $actuacion['foliosActuacion']['foliosActuacion'], 0, 1, 'L', FALSE);
	$ci->pdf->Cell(55, 6, 'Número de Actuación SICE : ', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(40, 6, $actuacion['referenciaActuacion'], 0, 0, 'L', FALSE);
	$ci->pdf->Cell(55, 6, 'Número de Actuación SGA (SIGEP) : ', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(40, 6, $actuacion['codigoActuacion'], 0, 1, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Iniciador :', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(170, 6, '('.$actuacion['iudIniciador'].') - '.$actuacion['nombreIniciador'], 0, 1, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Remitente :', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(170, 6, '('.$actuacion['iudIniciador'].') - '.$actuacion['nombreIniciador'], 0, 1, 'L', FALSE);
	$ci->pdf->Cell(45, 6, 'Area en la que se encuentra :', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(155, 6, $actuacion['nombreEstructuraActual'], 0, 1, 'L', FALSE);
	$ci->pdf->Cell(35, 6, 'Estado de Actuación :', 0, 0, 'L', FALSE);
	$ci->pdf->Cell(165, 6, $actuacion['nombreActuacionEstado'], 0, 1, 'L', FALSE);
	$ci->pdf->Cell(20, 6, 'Carátula : ', 0, 0, 'L', FALSE, FALSE, 0, FALSE, 'T', 'T');
	$ci->pdf->Multicell(180, 6, $actuacion['caratulaActuacion'], 0, 'L', false, 1, '', '', true, 0, true);
	$ci->pdf->Ln(2);
	$ci->pdf->SetFont('helvetica', 'B', 10);
	$ci->pdf->Cell(190, 7, 'Detalle de pases', 0, 1, 'L', TRUE);
	$ci->pdf->Ln(2);
	$ci->pdf->SetFont('helvetica', '', 9);
	$i = 1;
	$total = count($pases);
	$band = FALSE;
	foreach ($pases as $pase) {
		$ci->pdf->Cell(35, 6, 'Estado : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(155, 6, $pase['nombrePaseEstado'], 0, 1, 'L', FALSE);
		$ci->pdf->Cell(35, 6, 'Area Rtte. : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(155, 6, '('.$pase['iudOrigen'].') - '.$pase['nombreOrigen'], 0, 1, 'L', FALSE);
		$ci->pdf->Cell(35, 6, 'Fecha de envío : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(65, 6, GetDateTimeFromISO($pase['fechaEnvioActuacionPase']), 0, 0, 'L', FALSE);
		$ci->pdf->Cell(35, 6, 'Folios agregados : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(65, 6, $pase['foliosActuacionPase'], 0, 1, 'L', FALSE);
		$ci->pdf->Cell(35, 6, 'Agente Rtte. : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(155, 6, $pase['nombreCompletoPersonaOrigen'], 0, 1, 'L', FALSE);
		$ci->pdf->Cell(35, 6, 'Area u Org. Dest. : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(155, 6, '('.$pase['iudDestino'].') - '.$pase['nombreDestino'], 0, 1, 'L', FALSE);
		$ci->pdf->Cell(35, 6, 'Fecha de recepcion : ', 0, 0, 'L', FALSE);
		if($pase['fechaRecepcionActuacionPase'] != 0) {
			$ci->pdf->Cell(155, 6, GetDateTimeFromISO($pase['fechaRecepcionActuacionPase']), 0, 1, 'L', FALSE);
			if(!$fecha) {
				$fecha = date('Y-m-d H:i:s');
			}
			$band = FALSE;
			//$fecha = $pase['fechaRecepcionActuacionPase'];
			//$fecha = date('Y-m-d H:i:s');
		}
		else {
			$ci->pdf->Cell(155, 6, '', 0, 1, 'L', FALSE);
			$band = TRUE;
			$fecha = date('Y-m-d H:i:s');
		}
		$ci->pdf->Cell(35, 6, 'Agente Recep. : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(155, 6, $pase['nombreCompletoPersonaDestino'], 0, 1, 'L', FALSE);
		$ci->pdf->Cell(35, 6, 'Tiempo de gestión : ', 0, 0, 'L', FALSE);
		if($fecha != 0 && $band == FALSE) {
			$ultima = new DateTime($fecha);
			$anterior = new DateTime($pase['fechaRecepcionActuacionPase']);
			$intervalo = $anterior->diff($ultima);
			$ci->pdf->Cell(155, 6, $intervalo->format('%a días, %h horas %i minutos %s segundos'), 0, 1, 'L', FALSE);	
			$fecha = $pase['fechaRecepcionActuacionPase'];
		}
		else {
			$ci->pdf->Cell(155, 6, '', 0, 1, 'L', FALSE);	
		}
		
		$ci->pdf->Cell(35, 6, 'Observaciones : ', 0, 0, 'L', FALSE);
		$ci->pdf->Cell(155, 6, $pase['observacionActuacionPase'], 0, 1, 'L', FALSE);
		$ci->pdf->SetDrawColor(210, 210, 210);
		if($i != $total)  {
			$ci->pdf->Cell(190, 1, ' ', 'B', 1, 'L', FALSE);
			$ci->pdf->Ln(3)	;
		}
		$i = $i + 1;
		//if($pase['fechaRecepcionActuacionPase'] != 0) {
			//$fecha = $pase['fechaRecepcionActuacionPase'];
		//}
	}*/

	$ci->pdf->Output('example_001.pdf', 'I');
?> 